### ISSUE TITLE
Next Auth ([...nextauth] route.ts) Doesn't work on Localhost

### ISSUE THREAD

**Issue by josephna76** [vercel/nextjs-postgres-auth-starter#34]
The sign-up works but the sign-in doesn't on Localhost. Both sign-in and sign-up work on Vercel's hosted version.
The project was created using the one-click deployment to Vercel on Jun 23, 2023.

The message "Signed in as X" appears but the three dot loading state over the Sign In button does not end and the page gets stuck before getting to /protected.

I get this error - error TypeError [ERR_INVALID_URL]: Invalid URL. Am I unable to reach /protected despite being signed in because localhost is not an https route, whereas the Vercel deployed version is? http://localhost:3000/

**Comment by OldTucson** [comment]
same problem

**Comment by OldTucson** [comment]
> The sign-up works but the sign-in doesn't on Localhost. Both sign-in and sign-up work on Vercel's hosted version. The project was created using the one-click deployment to Vercel on Jun 23, 2023.
> 
> The message "Signed in as X" appears but the three dot loading state over the Sign In button does not end and the page gets stuck before getting to /protected.
> 
> I get this error - error TypeError [ERR_INVALID_URL]: Invalid URL. Am I unable to reach /protected despite being signed in because localhost is not an https route, whereas the Vercel deployed version is? http://localhost:3000/

i just fixed it by add 

NEXTAUTH_URL="http://localhost:3000"

to .env file

refer to [https://next-auth.js.org/tutorials/securing-pages-and-api-routes#using-gettoken](url)

**Comment by raychz** [comment]
Still doesnt work for me, even after setting NEXTAUTH_URL="http://localhost:3000/".

**Comment by rlfrahm** [comment]
The problem for me was that I had `Vercel="1"` in my .env file. Removing that solved my issue. This value came from `vercel env pull .env` automatically.

**Comment by leerob** [comment]
I am no longer seeing this with the new NextAuth.js beta https://github.com/vercel/nextjs-postgres-auth-starter/pull/48
